name: Barrier Release Build (macOS)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13  # Use Intel-based runner for better compatibility

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up environment
      run: |
        echo "TERM=xterm-256color" >> $GITHUB_ENV
        echo "B_BUILD_TYPE=Release" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        # Use Intel-based Homebrew paths
        brew update
        brew install qt@5 cmake create-dmg openssl
        
        # Set up Qt5 paths for Intel Mac
        export QT5_PREFIX=$(brew --prefix qt@5)
        echo "CMAKE_PREFIX_PATH=${QT5_PREFIX}" >> $GITHUB_ENV
        echo "Qt5_DIR=${QT5_PREFIX}/lib/cmake/Qt5" >> $GITHUB_ENV
        echo "PATH=${QT5_PREFIX}/bin:$PATH" >> $GITHUB_ENV

    - name: Verify Qt5 installation
      run: |
        echo "=== Qt5 installation check ==="
        QT5_PREFIX=$(brew --prefix qt@5)
        echo "Qt5 prefix: $QT5_PREFIX"
        ls -la "$QT5_PREFIX/lib/cmake/Qt5/" || echo "Qt5 cmake files not found"
        ls -la "$QT5_PREFIX/bin/" || echo "Qt5 binaries not found"

    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        
    - name: Build Barrier with Bundle
      run: |
        set -e
        set -x
        
        # Set up Qt5 environment
        QT5_PREFIX=$(brew --prefix qt@5)
        export CMAKE_PREFIX_PATH="$QT5_PREFIX"
        export Qt5_DIR="$QT5_PREFIX/lib/cmake/Qt5"
        export PATH="$QT5_PREFIX/bin:$PATH"
        
        # Create build directory
        mkdir -p build
        cd build
        
        # Configure CMake
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DBARRIER_BUILD_INSTALLER=ON \
              -DBARRIER_BUILD_TESTS=OFF \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 \
              -DCMAKE_PREFIX_PATH="$QT5_PREFIX" \
              -DQt5_DIR="$QT5_PREFIX/lib/cmake/Qt5" \
              ..
        
        # Build only the main targets
        make barrier barriers barrierc -j$(sysctl -n hw.ncpu)
        
        # Build the macOS bundle target
        make Barrier_MacOS

    - name: Verify bundle creation
      run: |
        echo "=== Looking for bundle directory ==="
        find . -name "bundle" -type d
        echo "=== Looking for Barrier.app ==="
        find . -name "Barrier.app" -type d
        echo "=== Bundle contents ==="
        if
