name: Barrier Release Build

on:
  push:
    tags:
      - 'v*.*.*'    # Trigger on tags like v2.4.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qtbase5-dev qt5-qmake qtbase5-dev-tools libssl-dev libcurl4-openssl-dev libavahi-compat-libdnssd-dev libx11-dev libxtst-dev libxinerama-dev libxss-dev libxi-dev

    - name: Build Barrier
      run: |
        ./clean_build.sh
        # Built files will be in ./build/bin

    - name: Package binaries
      run: |
        cd build/bin
        tar -czvf ../../barrier-linux-x64.tar.gz *
        cd ../..

    - name: Upload binaries as artifact
      uses: actions/upload-artifact@v4
      with:
        name: barrier-linux-x64
        path: barrier-linux-x64.tar.gz

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: barrier-linux-x64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}